<a href="https://colab.research.google.com/github/vanshuwjoshi/Learning-PyTorch/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. PyTorch Fundamentals

https://www.learnpytorch.io/00_pytorch_fundamentals/

In [1]:
import torch
print(torch.__version__)

2.3.0+cu121


### Introduction to Tensors

#### Creating tensors

PyTorch tensors are created using `torch.Tensor()`

#### Scalar

In [2]:
## scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

Scalar is a single number without any dimension.

In [4]:
## get tensor object as python int
scalar.item()

7

#### Vector

In [5]:
## vector
vector = torch.tensor([7, 8])
vector

tensor([7, 8])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

Vector is like an array with one row and therfore, ndim returns 1 and shape returns 2 as the length of the array.

#### Matrix

In [8]:
## MATRIX
MATRIX = torch.tensor([
    [7,8],
    [8,9]
])
MATRIX

tensor([[7, 8],
        [8, 9]])

All of these (scalar, vector, matrix) are TENSOR datatype

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX.shape

torch.Size([2, 2])

In [11]:
print(MATRIX[1])
print(MATRIX[0])

tensor([8, 9])
tensor([7, 8])


#### Tensor

In [12]:
## TENSOR
TENSOR = torch.tensor([
    [
        [1,2,3],
        [3,4,5],
        [7,8,9]
    ],
    [
        [5,6,7],
        [1,19,20],
        [7,8,12]
    ]
])
TENSOR

tensor([[[ 1,  2,  3],
         [ 3,  4,  5],
         [ 7,  8,  9]],

        [[ 5,  6,  7],
         [ 1, 19, 20],
         [ 7,  8, 12]]])

In [13]:
TENSOR.ndim

3

In [14]:
TENSOR.shape

torch.Size([2, 3, 3])

In [15]:
TENSOR[0] ## this is a matrix

tensor([[1, 2, 3],
        [3, 4, 5],
        [7, 8, 9]])

In [16]:
TENSOR[0][1] ## this is a vector

tensor([3, 4, 5])

In [17]:
TENSOR[0][1][0] ## this is a scalar

tensor(3)

TENSOR could be said as list of matrices, MATRIX could be called as list of vectors, and VECTOR could be called a list of scalars.

- scalar ndim = 0
- vector ndim = 1
- matirx ndim = 2
- tensor ndim = can be any number from 0 (scalar), 1 (vector), 2 (matrix), ...

Notations:
- scalar - a
- vector - y
- matrix - Q
- tensor - X

### Random Tensors

Why do we need random tensors?

Random Tensors are required as many Neural Networks start with tensors full of random numbers and the adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers -> so on`

In [18]:
## Create a random tensor of given size
random_tensor = torch.rand(4)
random_tensor

tensor([0.0207, 0.6221, 0.4514, 0.5946])

In [19]:
random_tensor1 = torch.rand(3,4)

## can say list of 2 matrices each of 3 rows and 4 columns
random_tensor2 = torch.rand(2,3,4)
print(random_tensor1)
print("Number of Dimensions: ", random_tensor1.ndim)
print("")
print(random_tensor2)
print("Number of Dimensions: ", random_tensor2.ndim)

tensor([[0.8140, 0.5347, 0.8330, 0.1887],
        [0.0958, 0.1890, 0.9658, 0.7309],
        [0.3333, 0.7153, 0.8173, 0.2176]])
Number of Dimensions:  2

tensor([[[0.7569, 0.2556, 0.6601, 0.5953],
         [0.0722, 0.9685, 0.3340, 0.1165],
         [0.1946, 0.7443, 0.2624, 0.8550]],

        [[0.9411, 0.3714, 0.6475, 0.6056],
         [0.4312, 0.5635, 0.7783, 0.4224],
         [0.5282, 0.7262, 0.1721, 0.3155]]])
Number of Dimensions:  3


#### Image Random Tensors

In [20]:
## Create a random tensor with similar shape to an image tensor
## color channel (RGB), height, width
random_image_size_tensor = torch.rand(3, 224, 224) ## 3 matrices 244 x 244
print(random_image_size_tensor.shape)
print(random_image_size_tensor.ndim)

torch.Size([3, 224, 224])
3


Therefore, we can say that any type of data can be converted into tensors.

### Zeros and Ones Tensors

In [21]:
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [22]:
zeros * random_tensor1

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [23]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

Note that by default tensors have float values.

In [24]:
ones * random_tensor1

tensor([[0.8140, 0.5347, 0.8330, 0.1887],
        [0.0958, 0.1890, 0.9658, 0.7309],
        [0.3333, 0.7153, 0.8173, 0.2176]])

### Creating a range of tensors and tensors-like

In [25]:
torch.arange(1, 11) ## returns tensor from [start, end)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [26]:
torch.arange(start=1, end=1000, step=77)

tensor([  1,  78, 155, 232, 309, 386, 463, 540, 617, 694, 771, 848, 925])

In [27]:
## Creating tensor-like
## to get say a zeros tensor of the same shape as other tensor
## without mentioning the shape of input tensor
one_to_ten = torch.arange(1, 11)
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [28]:
random_tensor1

tensor([[0.8140, 0.5347, 0.8330, 0.1887],
        [0.0958, 0.1890, 0.9658, 0.7309],
        [0.3333, 0.7153, 0.8173, 0.2176]])

In [29]:
## get 0 tensor as the shape of random_tensor1
torch.zeros_like(random_tensor1)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

### Tensor Datatype

3 big errors you'll run into in PyTorch and Deep Learning:
- dtype - Tensor datatype

 float32 (takes 32 bits of memory) is the default datatype. If we are ready to give up some precision we can go for float16 as it can compute faster. If we need more precision we can go for float64

 `tensor.dtype`
- device

  default - "cpu", can use "cuda", the tensors need to be on same device, like one tensor is created on GPU for faster calculations and one is created on CPU, this will create an error.

  `tensor.device`
- tensor shape

  `tensor.shape`

In [30]:
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None, ## data type
                               device=None, ## device of tensor
                               requires_grad=False ## track gradients with tensor operations
                               )

In [31]:
float_32_tensor.dtype

torch.float32

Even when we said dtype as None, it still makes it to default float32

In [32]:
## Convert float32 datatype to float16
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor.dtype

torch.float16

In [33]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

INTERESTING!! This works fine.

Just keep in mind this might create a problem in some cases.

#### Getting Tensor attributes - Data Type, Shape, Device

In [34]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.9618, 0.8864, 0.6898, 0.3106],
        [0.9678, 0.2270, 0.6549, 0.4010],
        [0.7932, 0.4998, 0.6382, 0.1778]])

In [35]:
print(some_tensor)
print(f"Data Type: {some_tensor.dtype}")
print(f"Shape: {some_tensor.shape}")
print(f"Device: {some_tensor.device}")

tensor([[0.9618, 0.8864, 0.6898, 0.3106],
        [0.9678, 0.2270, 0.6549, 0.4010],
        [0.7932, 0.4998, 0.6382, 0.1778]])
Data Type: torch.float32
Size: torch.Size([3, 4])
Device: cpu


### Manipulating Tensors (tensor operations)

Tensor operation include:
- Addition: `+` or `torch.add`
- Subtraction: `-` or `torch.subtract`
- Multiplication (element-wise): `*` or `torch.mul`
- Division: `/` or `torch.divide`
- Matrix Multiplication

In [36]:
## create a tensor and add 10 to it
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [39]:
## using pytorch functions add
torch.add(tensor, 10)

tensor([11, 12, 13])

In [38]:
## subtract a tensor by 10
tensor - 10

tensor([-9, -8, -7])

In [40]:
## using function subtract
torch.subtract(tensor, 10)

tensor([-9, -8, -7])

In [37]:
## multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [41]:
## using function mul
tensor.mul(10)

tensor([10, 20, 30])

In [42]:
## divide tensor by 10
tensor / 10

tensor([0.1000, 0.2000, 0.3000])

In [43]:
## using function divide
torch.divide(tensor, 10)

tensor([0.1000, 0.2000, 0.3000])

#### Matrix Multiplication

Two ways of performing multiplication in in NN and DL:
- Element-wise multiplication `torch.mul(tensor, tensor)`
- Matrix multiplication (dot product) `torch.matmul(tensor, tensor)` or `@`

Matrix Multiplication rules:
1. **Inner dimensions** must match:
* `(3,2) @ (3,2)` won't work
* `(3,2) @ (2,3)` will work
* `(2,3) @ (3,2)` will work

2. Resulting matrix has the shape of **Outer Dimensions**:
* `(3,2) @ (2,3)` => `(3,3)`
* `(2,3) @ (3,2)` => `(2,2)`

In [44]:
tensor

tensor([1, 2, 3])

In [45]:
## Element-wise multiplication
torch.mul(tensor, tensor)

tensor([1, 4, 9])

In [46]:
## Matrix-Multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [47]:
## THIS WON'T WORK
torch.matmul(torch.rand(3,2), torch.rand(3,2))

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [48]:
## Resulting matrix will be 2x2
torch.matmul(torch.rand(2,3), torch.rand(3,2))

tensor([[0.5715, 1.2630],
        [0.3330, 0.8585]])