<a href="https://colab.research.google.com/github/vanshuwjoshi/Learning-PyTorch/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. PyTorch Fundamentals

https://www.learnpytorch.io/00_pytorch_fundamentals/

In [1]:
import torch
print(torch.__version__)

2.3.0+cu121


### Introduction to Tensors

#### Creating tensors

PyTorch tensors are created using `torch.Tensor()`

#### Scalar

In [2]:
## scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

Scalar is a single number without any dimension.

In [4]:
## get tensor object as python int
scalar.item()

7

#### Vector

In [5]:
## vector
vector = torch.tensor([7, 8])
vector

tensor([7, 8])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

Vector is like an array with one row and therfore, ndim returns 1 and shape returns 2 as the length of the array.

#### Matrix

In [8]:
## MATRIX
MATRIX = torch.tensor([
    [7,8],
    [8,9]
])
MATRIX

tensor([[7, 8],
        [8, 9]])

All of these (scalar, vector, matrix) are TENSOR datatype

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX.shape

torch.Size([2, 2])

In [11]:
print(MATRIX[1])
print(MATRIX[0])

tensor([8, 9])
tensor([7, 8])


#### Tensor

In [12]:
## TENSOR
TENSOR = torch.tensor([
    [
        [1,2,3],
        [3,4,5],
        [7,8,9]
    ],
    [
        [5,6,7],
        [1,19,20],
        [7,8,12]
    ]
])
TENSOR

tensor([[[ 1,  2,  3],
         [ 3,  4,  5],
         [ 7,  8,  9]],

        [[ 5,  6,  7],
         [ 1, 19, 20],
         [ 7,  8, 12]]])

In [13]:
TENSOR.ndim

3

In [14]:
TENSOR.shape

torch.Size([2, 3, 3])

In [15]:
TENSOR[0] ## this is a matrix

tensor([[1, 2, 3],
        [3, 4, 5],
        [7, 8, 9]])

In [16]:
TENSOR[0][1] ## this is a vector

tensor([3, 4, 5])

In [17]:
TENSOR[0][1][0] ## this is a scalar

tensor(3)

TENSOR could be said as list of matrices, MATRIX could be called as list of vectors, and VECTOR could be called a list of scalars.

- scalar ndim = 0
- vector ndim = 1
- matirx ndim = 2
- tensor ndim = can be any number from 0 (scalar), 1 (vector), 2 (matrix), ...

Notations:
- scalar - a
- vector - y
- matrix - Q
- tensor - X

### Random Tensors

Why do we need random tensors?

Random Tensors are required as many Neural Networks start with tensors full of random numbers and the adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers -> so on`

In [18]:
## Create a random tensor of given size
random_tensor = torch.rand(4)
random_tensor

tensor([0.7289, 0.6692, 0.0450, 0.4414])

In [19]:
random_tensor1 = torch.rand(3,4)

## can say list of 2 matrices each of 3 rows and 4 columns
random_tensor2 = torch.rand(2,3,4)
print(random_tensor1)
print("Number of Dimensions: ", random_tensor1.ndim)
print("")
print(random_tensor2)
print("Number of Dimensions: ", random_tensor2.ndim)

tensor([[0.0353, 0.0822, 0.7913, 0.7273],
        [0.0028, 0.0815, 0.1691, 0.2044],
        [0.6990, 0.5198, 0.4155, 0.4851]])
Number of Dimensions:  2

tensor([[[0.1007, 0.0189, 0.6471, 0.0771],
         [0.2670, 0.2456, 0.0544, 0.8672],
         [0.7207, 0.3649, 0.3766, 0.6040]],

        [[0.8045, 0.8861, 0.0660, 0.1008],
         [0.5595, 0.1251, 0.3429, 0.6404],
         [0.1437, 0.8565, 0.4548, 0.8893]]])
Number of Dimensions:  3


#### Image Random Tensors

In [20]:
## Create a random tensor with similar shape to an image tensor
## color channel (RGB), height, width
random_image_size_tensor = torch.rand(3, 224, 224) ## 3 matrices 244 x 244
print(random_image_size_tensor.shape)
print(random_image_size_tensor.ndim)

torch.Size([3, 224, 224])
3


Therefore, we can say that any type of data can be converted into tensors.

### Zeros and Ones Tensors

In [21]:
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [22]:
zeros * random_tensor1

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [23]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

Note that by default tensors have float values.

In [24]:
ones * random_tensor1

tensor([[0.0353, 0.0822, 0.7913, 0.7273],
        [0.0028, 0.0815, 0.1691, 0.2044],
        [0.6990, 0.5198, 0.4155, 0.4851]])

### Creating a range of tensors and tensors-like

In [25]:
torch.arange(1, 11) ## returns tensor from [start, end)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [26]:
torch.arange(start=1, end=1000, step=77)

tensor([  1,  78, 155, 232, 309, 386, 463, 540, 617, 694, 771, 848, 925])

In [27]:
## Creating tensor-like
## to get say a zeros tensor of the same shape as other tensor
## without mentioning the shape of input tensor
one_to_ten = torch.arange(1, 11)
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [28]:
random_tensor1

tensor([[0.0353, 0.0822, 0.7913, 0.7273],
        [0.0028, 0.0815, 0.1691, 0.2044],
        [0.6990, 0.5198, 0.4155, 0.4851]])

In [29]:
## get 0 tensor as the shape of random_tensor1
torch.zeros_like(random_tensor1)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

### Tensor Datatype

3 big errors you'll run into in PyTorch and Deep Learning:
- dtype - Tensor datatype

 float32 (takes 32 bits of memory) is the default datatype. If we are ready to give up some precision we can go for float16 as it can compute faster. If we need more precision we can go for float64

 `tensor.dtype`
- device

  default - "cpu", can use "cuda", the tensors need to be on same device, like one tensor is created on GPU for faster calculations and one is created on CPU, this will create an error.

  `tensor.device`
- tensor shape

  `tensor.shape`

In [30]:
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None, ## data type
                               device=None, ## device of tensor
                               requires_grad=False ## track gradients with tensor operations
                               )

In [31]:
float_32_tensor.dtype

torch.float32

Even when we said dtype as None, it still makes it to default float32

In [32]:
## Convert float32 datatype to float16
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor.dtype

torch.float16

In [33]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

INTERESTING!! This works fine.

Just keep in mind this might create a problem in some cases.

#### Getting Tensor attributes - Data Type, Shape, Device

In [34]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.5023, 0.4469, 0.9051, 0.5906],
        [0.0178, 0.8936, 0.8216, 0.6970],
        [0.1629, 0.2043, 0.4037, 0.1455]])

In [35]:
print(some_tensor)
print(f"Data Type: {some_tensor.dtype}")
print(f"Shape: {some_tensor.shape}")
print(f"Device: {some_tensor.device}")

tensor([[0.5023, 0.4469, 0.9051, 0.5906],
        [0.0178, 0.8936, 0.8216, 0.6970],
        [0.1629, 0.2043, 0.4037, 0.1455]])
Data Type: torch.float32
Shape: torch.Size([3, 4])
Device: cpu


### Manipulating Tensors (tensor operations)

Tensor operation include:
- Addition: `+` or `torch.add`
- Subtraction: `-` or `torch.subtract`
- Multiplication (element-wise): `*` or `torch.mul`
- Division: `/` or `torch.divide`
- Matrix Multiplication

In [36]:
## create a tensor and add 10 to it
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [37]:
## using pytorch functions add
torch.add(tensor, 10)

tensor([11, 12, 13])

In [38]:
## subtract a tensor by 10
tensor - 10

tensor([-9, -8, -7])

In [39]:
## using function subtract
torch.subtract(tensor, 10)

tensor([-9, -8, -7])

In [40]:
## multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [41]:
## using function mul
tensor.mul(10)

tensor([10, 20, 30])

In [42]:
## divide tensor by 10
tensor / 10

tensor([0.1000, 0.2000, 0.3000])

In [43]:
## using function divide
torch.divide(tensor, 10)

tensor([0.1000, 0.2000, 0.3000])

#### Matrix Multiplication

Two ways of performing multiplication in in NN and DL:
- Element-wise multiplication `torch.mul(tensor, tensor)`
- Matrix multiplication (dot product) `torch.matmul(tensor, tensor)` or `@` or `torch.mm(tensor, tensor)`

Matrix Multiplication rules:
1. **Inner dimensions** must match:
* `(3,2) @ (3,2)` won't work
* `(3,2) @ (2,3)` will work
* `(2,3) @ (3,2)` will work

2. Resulting matrix has the shape of **Outer Dimensions**:
* `(3,2) @ (2,3)` => `(3,3)`
* `(2,3) @ (3,2)` => `(2,2)`

In [44]:
tensor

tensor([1, 2, 3])

In [45]:
## Element-wise multiplication
torch.mul(tensor, tensor)

tensor([1, 4, 9])

In [46]:
## Matrix-Multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [47]:
## THIS WON'T WORK
## torch.matmul(torch.rand(3,2), torch.rand(3,2))

In [48]:
## Resulting matrix will be 2x2
torch.matmul(torch.rand(2,3), torch.rand(3,2))

tensor([[0.7441, 0.8644],
        [0.6890, 0.9868]])

#### Shape Errors in DL and Matrix Transpose

In [49]:
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])

tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

Therefore, we will not be able to multiply these tensors or matrices.

What we need is **Transpose** of a matrix.

In [50]:
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [51]:
tensor_B.T.shape

torch.Size([2, 3])

In [52]:
torch.matmul(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [53]:
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape}, tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape}, here inner dimensions match!!")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]), here inner dimensions match!!
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


#### Tensor Aggregation

Finding min, max, mean, sum and so on

- `tensor.min()` OR `torch.min(tensor)`
- `tensor.max()` OR `torch.max(tensor)`
- `tensor.type(torch.float32).mean()` OR `torch.mean(tensor.type(torch.float32))`
- `tensor.sum()` OR `torch.sum(tensor)`

In [54]:
tensor = torch.arange(0, 100, 10)
tensor

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [55]:
torch.min(tensor) ## or tensor.min()

tensor(0)

In [56]:
torch.max(tensor) ## or tensor.max()

tensor(90)

In [57]:
## This following code will not work as the dtype of input tensor is Long
## We need to convert it to floating point

##torch.mean(tensor)

In [58]:
torch.mean(tensor.type(torch.float32)) ## or tensor.type(torch.float32).mean()

tensor(45.)

*torch.mean() requires a tensor of float data type to work.*

In [59]:
torch.sum(tensor) ## or tensor.sum()

tensor(450)

Find the position of min and max of a tensor.

- `tensor.argmin()`
- `tensor.argmax()`

In [60]:
output

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [61]:
output.argmin()

tensor(0)

In [62]:
output.argmax()

tensor(8)

#### Reshaping, Stacking, Squeezing and Unsqueezing tensors

* Reshaping - reshape an input tensor into a defined shape `x.reshape()`
* View - Return a view of an input tensor of a certain shape but keep the same memory as the original tensor.
* Stacking - combine multiple tensors on top of each other or side by side, `torch.stack()`, `torch.hstack()`, `torch.vstack()`
* Squeezing - removes all `1` dimensions from a tensor
* Unsqueezing - add a `1` dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [63]:
x = torch.arange(1.,10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [64]:
x.reshape(1,9), x.reshape(1,9).shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [65]:
x.reshape(9, 1), x.reshape(9, 1).shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

Cannot do some other shape like reshape(1,8) (fitting 9 elements to 8 places) or reshape(2,9) (fitting 9 elements into 18 places).  

In [66]:
y = torch.arange(0.,10.)
y, y.shape

(tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([10]))

In [67]:
## Can fit 10 elements into 2 tensors of size 5
y.reshape(2,5)

tensor([[0., 1., 2., 3., 4.],
        [5., 6., 7., 8., 9.]])

In [68]:
## Change the view
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

Changing z changes x as view of a tensor shares the same memory as the original tensor.

In [69]:
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

**Stacking of tensors** -

`torch.stack()`
- Concatenates a sequence of tensors along a new dimension.
- All tensors need to be of the same size.

`dim` - Has to be between 0 and the number of dimensions of concatenated tensors (inclusive). Default: 0

In [70]:
## Stacking of Tensors
torch.stack([x,x,x,x]) ## dim=0 by default

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [71]:
## dim = 1
torch.stack([x,x,x,x], dim=1)

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [72]:
output

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [73]:
torch.stack([output, output], dim=0)

tensor([[[ 27,  30,  33],
         [ 61,  68,  75],
         [ 95, 106, 117]],

        [[ 27,  30,  33],
         [ 61,  68,  75],
         [ 95, 106, 117]]])

In [74]:
torch.stack([output, output], dim=1)

tensor([[[ 27,  30,  33],
         [ 27,  30,  33]],

        [[ 61,  68,  75],
         [ 61,  68,  75]],

        [[ 95, 106, 117],
         [ 95, 106, 117]]])

In [75]:
torch.stack([output, output], dim=2)

tensor([[[ 27,  27],
         [ 30,  30],
         [ 33,  33]],

        [[ 61,  61],
         [ 68,  68],
         [ 75,  75]],

        [[ 95,  95],
         [106, 106],
         [117, 117]]])

`torch.hstack()` - Stack tensors in sequence horizontally (column wise).

This is equivalent to concatenation along the first axis for 1-D tensors, and along the second axis for all other tensors.

In [76]:
torch.hstack([x,x])

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9., 5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [77]:
torch.hstack([output, output])

tensor([[ 27,  30,  33,  27,  30,  33],
        [ 61,  68,  75,  61,  68,  75],
        [ 95, 106, 117,  95, 106, 117]])

`torch.vstack()` - Stack tensors in sequence vertically (row wise).

This is equivalent to concatenation along the first axis after all 1-D tensors have been reshaped by torch.atleast_2d().

In [78]:
torch.vstack([x,x])

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [79]:
torch.vstack([output, output])

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117],
        [ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

`torch.squeeze(tensor)` or `tensor.squeeze()` - Returns a tensor with all specified dimensions of input of size 1 removed.

In [82]:
x, x.shape

(tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [84]:
x.reshape(1,9), x.reshape(1,9).shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [85]:
x.reshape(1,9).squeeze(), x.reshape(1,9).squeeze().shape

(tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

Removes all the single dimensions of the tensor, however, we can also specify to remove a particular dimension as well.

In [89]:
TENSOR = torch.tensor([
    [
        [1],
        [3],
        [7]
    ],
])
TENSOR, TENSOR.shape

(tensor([[[1],
          [3],
          [7]]]),
 torch.Size([1, 3, 1]))

In [90]:
TENSOR.squeeze(), TENSOR.squeeze().shape

(tensor([1, 3, 7]), torch.Size([3]))

In [91]:
## Removing the 0th dim
TENSOR.squeeze(dim=0), TENSOR.squeeze(dim=0).shape

(tensor([[1],
         [3],
         [7]]),
 torch.Size([3, 1]))

In [94]:
## removing the 1st dim ---- will not do anything as it is not 1
TENSOR.squeeze(dim=1), TENSOR.squeeze(dim=1).shape

(tensor([[[1],
          [3],
          [7]]]),
 torch.Size([1, 3, 1]))

In [93]:
## removing the 2nd dim
TENSOR.squeeze(dim=2), TENSOR.squeeze(dim=2).shape

(tensor([[1, 3, 7]]), torch.Size([1, 3]))

`tensor.unsqueeze(dim)` or `torch.unsqueeze(tensor, dim)` - Returns a new tensor with a dimension of size one inserted at the specified position.

A dim value within the range `[-input.dim() - 1, input.dim() + 1)` can be used. Negative dim will correspond to unsqueeze() applied at `dim = dim + input.dim() + 1`.

In [99]:
TENSOR_squeezed = TENSOR.squeeze()
TENSOR_squeezed, TENSOR_squeezed.shape, TENSOR_squeezed.dim()

(tensor([1, 3, 7]), torch.Size([3]), 1)

here, dim = [-2, 2)

In [96]:
TENSOR_squeezed.unsqueeze(0), TENSOR_squeezed.unsqueeze(0).shape

(tensor([[1, 3, 7]]), torch.Size([1, 3]))

In [97]:
TENSOR_squeezed.unsqueeze(1), TENSOR_squeezed.unsqueeze(1).shape

(tensor([[1],
         [3],
         [7]]),
 torch.Size([3, 1]))

`torch.permute(dim)` or `tensor.permute(dim)` - Returns a view (shares the same memory of original tensor) of the original tensor input with its dimensions permuted. It rearranges the dimensions to the new dim you want.

In [102]:
TENSOR = torch.rand(size=(2,4,2))
TENSOR, TENSOR.shape

(tensor([[[0.6854, 0.3215],
          [0.4931, 0.4182],
          [0.0730, 0.9704],
          [0.1698, 0.6553]],
 
         [[0.1437, 0.8504],
          [0.4282, 0.2899],
          [0.7576, 0.4150],
          [0.0965, 0.2018]]]),
 torch.Size([2, 4, 2]))

In [103]:
TENSOR_permuted = TENSOR.permute(2,0,1) ## shifts dim 0->1, 1->2, and 2->0
TENSOR_permuted, TENSOR_permuted.shape

(tensor([[[0.6854, 0.4931, 0.0730, 0.1698],
          [0.1437, 0.4282, 0.7576, 0.0965]],
 
         [[0.3215, 0.4182, 0.9704, 0.6553],
          [0.8504, 0.2899, 0.4150, 0.2018]]]),
 torch.Size([2, 2, 4]))

In [107]:
TENSOR[0,0,0] = 0
TENSOR

tensor([[[0.0000, 0.3215],
         [0.4931, 0.4182],
         [0.0730, 0.9704],
         [0.1698, 0.6553]],

        [[0.1437, 0.8504],
         [0.4282, 0.2899],
         [0.7576, 0.4150],
         [0.0965, 0.2018]]])

In [108]:
TENSOR_permuted

tensor([[[0.0000, 0.4931, 0.0730, 0.1698],
         [0.1437, 0.4282, 0.7576, 0.0965]],

        [[0.3215, 0.4182, 0.9704, 0.6553],
         [0.8504, 0.2899, 0.4150, 0.2018]]])

Since, the permuted TENSOR is a view, therefore, a change in TENSOR will change in permuted as well and vice versa.