<a href="https://colab.research.google.com/github/vanshuwjoshi/Learning-PyTorch/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. PyTorch Fundamentals

https://www.learnpytorch.io/00_pytorch_fundamentals/

In [ ]:
import torch
print(torch.__version__)

2.3.0+cu121


### Introduction to Tensors

#### Creating tensors

PyTorch tensors are created using `torch.Tensor()`

#### Scalar

In [ ]:
## scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

Scalar is a single number without any dimension.

In [ ]:
## get tensor object as python int
scalar.item()

7

#### Vector

In [ ]:
## vector
vector = torch.tensor([7, 8])
vector

tensor([7, 8])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

Vector is like an array with one row and therfore, ndim returns 1 and shape returns 2 as the length of the array.

#### Matrix

In [ ]:
## MATRIX
MATRIX = torch.tensor([
    [7,8],
    [8,9]
])
MATRIX

tensor([[7, 8],
        [8, 9]])

All of these (scalar, vector, matrix) are TENSOR datatype

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
print(MATRIX[1])
print(MATRIX[0])

tensor([8, 9])
tensor([7, 8])


#### Tensor

In [ ]:
## TENSOR
TENSOR = torch.tensor([
    [
        [1,2,3],
        [3,4,5],
        [7,8,9]
    ],
    [
        [5,6,7],
        [1,19,20],
        [7,8,12]
    ]
])
TENSOR

tensor([[[ 1,  2,  3],
         [ 3,  4,  5],
         [ 7,  8,  9]],

        [[ 5,  6,  7],
         [ 1, 19, 20],
         [ 7,  8, 12]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([2, 3, 3])

In [ ]:
TENSOR[0] ## this is a matrix

tensor([[1, 2, 3],
        [3, 4, 5],
        [7, 8, 9]])

In [ ]:
TENSOR[0][1] ## this is a vector

tensor([3, 4, 5])

In [ ]:
TENSOR[0][1][0] ## this is a scalar

tensor(3)

TENSOR could be said as list of matrices, MATRIX could be called as list of vectors, and VECTOR could be called a list of scalars.

- scalar ndim = 0
- vector ndim = 1
- matirx ndim = 2
- tensor ndim = can be any number from 0 (scalar), 1 (vector), 2 (matrix), ...

Notations:
- scalar - a
- vector - y
- matrix - Q
- tensor - X

### Random Tensors

Why do we need random tensors?

Random Tensors are required as many Neural Networks start with tensors full of random numbers and the adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers -> so on`

In [ ]:
## Create a random tensor of given size
random_tensor = torch.rand(4)
random_tensor

tensor([0.7421, 0.8034, 0.1431, 0.4739])

In [ ]:
random_tensor1 = torch.rand(3,4)

## can say list of 2 matrices each of 3 rows and 4 columns
random_tensor2 = torch.rand(2,3,4)
print(random_tensor1)
print("Number of Dimensions: ", random_tensor1.ndim)
print("")
print(random_tensor2)
print("Number of Dimensions: ", random_tensor2.ndim)

tensor([[0.5912, 0.3303, 0.4463, 0.6288],
        [0.9963, 0.1614, 0.3664, 0.5379],
        [0.6130, 0.6281, 0.9778, 0.0526]])
Number of Dimensions:  2

tensor([[[0.1777, 0.8721, 0.0499, 0.7263],
         [0.3319, 0.5078, 0.1329, 0.5720],
         [0.5451, 0.5631, 0.3253, 0.6035]],

        [[0.5279, 0.6648, 0.1355, 0.6162],
         [0.7781, 0.4411, 0.5363, 0.1251],
         [0.6583, 0.2735, 0.9197, 0.9871]]])
Number of Dimensions:  3


#### Image Random Tensors

In [ ]:
## Create a random tensor with similar shape to an image tensor
## color channel (RGB), height, width
random_image_size_tensor = torch.rand(3, 224, 224) ## 3 matrices 244 x 244
print(random_image_size_tensor.shape)
print(random_image_size_tensor.ndim)

torch.Size([3, 224, 224])
3


Therefore, we can say that any type of data can be converted into tensors.

### Zeros and Ones Tensors

In [ ]:
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zeros * random_tensor1

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

Note that by default tensors have float values.

In [ ]:
ones * random_tensor1

tensor([[0.5912, 0.3303, 0.4463, 0.6288],
        [0.9963, 0.1614, 0.3664, 0.5379],
        [0.6130, 0.6281, 0.9778, 0.0526]])

### Creating a range of tensors and tensors-like

In [ ]:
torch.arange(1, 11) ## returns tensor from [start, end)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
torch.arange(start=1, end=1000, step=77)

tensor([  1,  78, 155, 232, 309, 386, 463, 540, 617, 694, 771, 848, 925])

In [ ]:
## Creating tensor-like
## to get say a zeros tensor of the same shape as other tensor
## without mentioning the shape of input tensor
one_to_ten = torch.arange(1, 11)
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
random_tensor1

tensor([[0.5912, 0.3303, 0.4463, 0.6288],
        [0.9963, 0.1614, 0.3664, 0.5379],
        [0.6130, 0.6281, 0.9778, 0.0526]])

In [ ]:
## get 0 tensor as the shape of random_tensor1
torch.zeros_like(random_tensor1)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

### Tensor Datatype

3 big errors you'll run into in PyTorch and Deep Learning:
- dtype - Tensor datatype

 float32 (takes 32 bits of memory) is the default datatype. If we are ready to give up some precision we can go for float16 as it can compute faster. If we need more precision we can go for float64
- device

  default - "cpu", can use "cuda", the tensors need to be on same device, like one tensor is created on GPU for faster calculations and one is created on CPU, this will create an error.
- tensor shape

In [ ]:
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None, ## data type
                               device=None, ## device of tensor
                               requires_grad=False ## track gradients with tensor operations
                               )

In [ ]:
float_32_tensor.dtype

torch.float32

Even when we said dtype as None, it still makes it to default float32

In [ ]:
## Convert float32 datatype to float16
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor.dtype

torch.float16